# Generated by Django 2.0.6 on 2018-10-02 16:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_price', models.FloatField()),
                ('item_mnfctr_date', models.DateField(null=True)),
                ('item_expiry_date', models.DateField(null=True)),
                ('item_comp_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_number', models.CharField(max_length=6)),
                ('truck_driver', models.CharField(max_length=30)),
                ('truck_village1', models.CharField(max_length=20)),
                ('truck_village2', models.CharField(max_length=20)),
                ('truck_village3', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ware_house',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ware_place', models.CharField(max_length=30)),
            ],
        ),
        migrations.AddField(
            model_name='truck',
            name='t_ware_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tware_id', to='shop.ware_house'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_truck_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itruck_id', to='shop.truck'),
        ),
        migrations.AddField(
            model_name='item',
            name='i_ware_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='iware_id', to='shop.ware_house'),
        ),
    ]
