# Generated by Django 2.0.6 on 2018-10-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='truck',
            name='truck_name',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='truck',
            name='truck_password',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AddField(
            model_name='ware_house',
            name='ware_password',
            field=models.CharField(default=None, max_length=30),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_number',
            field=models.CharField(max_length=6, unique=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_village1',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_village2',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='truck',
            name='truck_village3',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='ware_house',
            name='ware_place',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
