# Generated by Django 2.0.6 on 2018-10-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_item_item_barcode'),
    ]

    operations = [
        migrations.CreateModel(
            name='procure_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proc_item', models.CharField(choices=[('Banana', 'Banana'), ('Onion', 'Onion'), ('Rice', 'Rice'), ('Ragi', 'Ragi'), ('Corn', 'Corn'), ('Tomato', 'Tomato'), ('Coconut', 'Coconut'), ('Ginger', 'Ginger'), ('Arecanut', 'Arecanut'), ('Grapes', 'Grapes')], max_length=20)),
                ('proc_item_price', models.FloatField()),
                ('proc_item_weight', models.FloatField()),
            ],
        ),
    ]
