# Generated by Django 2.0.6 on 2018-10-04 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_remove_procure_item_proc_item_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='procure_item',
            name='proc_quantity',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='procure_item',
            name='proc_total_price',
            field=models.FloatField(default=0),
        ),
    ]
