# Generated by Django 2.0.6 on 2018-10-05 09:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_auto_20181004_1912'),
    ]

    operations = [
        migrations.CreateModel(
            name='quantity_truck',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant_truck', models.IntegerField(default=0)),
                ('quant_truck_qwid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quant_truck_qwid', to='shop.ware_house')),
                ('quant_truck_tid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quant_truck_tid', to='shop.truck')),
            ],
        ),
        migrations.CreateModel(
            name='quantity_ware',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quant_ware', models.IntegerField(default=0)),
                ('quant_ware_iid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quant_ware_iid', to='shop.item')),
                ('quant_ware_wid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quant_ware_wid', to='shop.ware_house')),
            ],
        ),
    ]
