# Generated by Django 2.0.6 on 2018-10-05 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_quantity_truck_quantity_ware'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quantity_truck',
            name='quant_truck_qwid',
        ),
        migrations.RemoveField(
            model_name='quantity_truck',
            name='quant_truck_tid',
        ),
        migrations.RemoveField(
            model_name='quantity_ware',
            name='quant_ware_iid',
        ),
        migrations.RemoveField(
            model_name='quantity_ware',
            name='quant_ware_wid',
        ),
        migrations.AddField(
            model_name='item',
            name='item_quantity_truck',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='item',
            name='item_quantity_ware',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='quantity_truck',
        ),
        migrations.DeleteModel(
            name='quantity_ware',
        ),
    ]
