# Generated by Django 2.0.6 on 2018-07-04 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='bidding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('b_price', models.FloatField()),
                ('b_description', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='dept_master',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('d_name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='sub_dept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sub_dept_name', models.CharField(max_length=30)),
                ('D_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_id', to='tender.dept_master')),
            ],
        ),
        migrations.CreateModel(
            name='tender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=30)),
                ('t_description', models.CharField(max_length=100)),
                ('t_start_period', models.DateTimeField(null=True)),
                ('t_price', models.FloatField()),
                ('t_end_date', models.DateTimeField(null=True)),
                ('D_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_id1', to='tender.dept_master')),
                ('Sub_Id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_department_id', to='tender.sub_dept')),
            ],
        ),
        migrations.AddField(
            model_name='bidding',
            name='t_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tender_id', to='tender.tender'),
        ),
    ]
