# Generated by Django 2.0.6 on 2018-07-04 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tender',
            name='t_image',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
