# Generated by Django 2.0.6 on 2018-07-05 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0002_tender_t_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=30)),
                ('reg_nmbr', models.CharField(max_length=12, unique=True)),
                ('c_password', models.CharField(max_length=12)),
                ('c_repassword', models.CharField(max_length=12)),
                ('c_email', models.CharField(max_length=254)),
            ],
        ),
    ]
