# Generated by Django 2.0.6 on 2018-07-05 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0003_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='company',
        ),
    ]
