# Generated by Django 2.0.6 on 2018-07-05 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0004_delete_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='dept_master',
            name='d_image',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='sub_dept',
            name='sub_image',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
