# Generated by Django 2.0.6 on 2018-07-06 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0005_auto_20180705_1758'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dept_master',
            name='d_image',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='sub_dept',
            name='sub_image',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='tender',
            name='t_image',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
