# Generated by Django 2.0.6 on 2018-07-06 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0008_auto_20180706_1012'),
    ]

    operations = [
        migrations.AddField(
            model_name='bidding',
            name='c_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_id', to='tender.company'),
        ),
    ]
