# Generated by Django 2.0.6 on 2018-07-06 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0013_auto_20180706_1636'),
    ]

    operations = [
        migrations.RenameField(
            model_name='company',
            old_name='c_user_id',
            new_name='c_user',
        ),
    ]
