# Generated by Django 2.0.6 on 2018-07-06 14:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0014_auto_20180706_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='c_user',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='company_user', to=settings.AUTH_USER_MODEL),
        ),
    ]
