# Generated by Django 2.0.6 on 2018-07-07 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tender', '0015_auto_20180706_2022'),
    ]

    operations = [
        migrations.CreateModel(
            name='complaint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('compl_name', models.CharField(max_length=30, null=True)),
                ('compl_description', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='company',
            name='c_user',
        ),
    ]
